### ISSUE TITLE
The source of these parser files

### ISSUE THREAD

**Issue by gilgamsh** [eclufsc/libertyParser#2]
I am interested in where is the source of these parser files. In which site can I find these things?

**Comment by tarberd** [comment]
Hi @gilgamsh,

I am sorry but I do not remember fully. 
I remember you need to create an account at their website and only then you can download it.
I did a quick google and found this [link](https://www.synopsys.com/community/interoperability-programs/tap-in.html).
Maybe give it a try?

**Comment by gilgamsh** [comment]
Thank  you very much.
